name: push and deploy

on:
  push:
    branches:
      - env-test

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'

      - name: uruchom Å›rodowisko docker-compose
        env:
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          #DB
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_DB}}
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-remote.yml -p remote-prge up --build -d


#      - name: Login to GHCR
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{github.actor}}
#          password: ${{secrets.GITHUB_TOKEN}}
#
#      - name: Set up Build
#        run: |
#          docker buildx build \
#          -t ghcr.io/${{github.repository_owner}}

